name: craft_dynamic
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  archive: ^3.3.2
  cached_network_image: ^3.2.3
  camera: ^0.10.0+4
  date_format: ^2.0.7
  dio: ^5.1.1
  dropdown_button2: ^1.9.1
  encrypt: ^5.0.1
  floor: ^1.3.0
  floor_generator: ^1.3.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_secure_storage: ^6.0.0
  fluttercontactpicker: ^4.7.0
  group_button: ^5.2.2
  hex: ^0.2.0
  image_picker: ^0.8.6
  intl: any
  local_auth: ^2.1.2
  logger: ^1.1.0
  lottie: ^2.0.0
  package_info_plus: ^4.0.2
  path_provider: ^2.0.11
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  unique_identifier: ^0.2.0
  url_launcher: ^6.1.7
  uuid: ^3.0.6
  vibration: ^1.7.6
  # mobile_scanner: ^2.1.0
  flutter_jailbreak_detection: ^1.8.0
  local_session_timeout: ^2.1.1
  get: ^4.6.5
  fluttertoast: any
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  yaml: ^3.1.1
  json_annotation: ^4.8.0
  json_serializable: ^6.6.0
  flutter_spinkit: ^5.1.0
  badges: ^3.0.2
  rsa_encrypt: ^2.0.0
  asn1lib: ^1.4.0
  pointycastle: ^3.6.2
  pem: ^2.0.2
  # pattern_formatter: any
  convert: ^3.1.1
  crypto: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  easy_localization: ^3.0.1
  connectivity_plus: ^3.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  platform_device_id: ^1.0.1
  flutter_multi_formatter: ^2.11.0
  blur: ^3.1.0
  logging: ^1.2.0
  steel_crypt: ^3.0.0+1
  syncfusion_flutter_pdf: 21.2.8 
  flutter_pdfview: ^1.3.1
  share_plus: ^7.0.2
  open_file: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/craft_dynamic/assets/lottie/loading.json
    - packages/craft_dynamic/assets/lottie/loading_list.json
    - packages/craft_dynamic/assets/lottie/error.json
    - packages/craft_dynamic/assets/lottie/success.json
    - packages/craft_dynamic/assets/lottie/information.json
    - packages/craft_dynamic/assets/images/fingerprint.png
    - packages/craft_dynamic/assets/images/qr-code.png
    - packages/craft_dynamic/assets/lottie/info_lottie.json
    - packages/craft_dynamic/assets/images/warning.png
    - packages/craft_dynamic/assets/images/empty.png

  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
